#!/usr/bin/env python3

# MIT License

# Copyright (c) 2020 Yitzchak Schwarz

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import os, sys, time
from xdg import BaseDirectory
from gi.repository import GLib, Gio
from pydbus import SystemBus

from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# DBus:
bus = SystemBus()

# Accounts proxy object:
accounts = bus.get('org.freedesktop.Accounts', '/org/freedesktop/Accounts')

#Get current user's dbus path:
user_name = GLib.get_user_name()
user = accounts.FindUserByName(user_name)

# User account proxy object:
up = bus.get('org.freedesktop.Accounts', user)

class NitrogenHandler(FileSystemEventHandler):
	def on_modified(self, event):
		apply_background()

def apply_background():
	for line in open(os.path.join(BaseDirectory.load_first_config("nitrogen"), "bg-saved.cfg"), "r").readlines():
		if line.startswith("file="):
			# Get the picture file:
			file = line.split("=")[1].strip()
			
			# Set current user's background picture file across the system:
			up.SetBackgroundFile(file) # User Account
			up.Set("org.freedesktop.DisplayManager.AccountsService", "BackgroundFile", GLib.Variant ('s', (file))) # Display Manager
			Gio.Settings.new("org.gnome.desktop.background").set_string("picture-uri", file) # GSettings

			return

if __name__ == "__main__":
	apply_background()
	
	if "-d" in sys.argv:
		# Run in the background and apply changes as they happen:
		observer = Observer()
		observer.schedule(NitrogenHandler(), path=BaseDirectory.load_first_config("nitrogen"), recursive=False)
		observer.start()

		try:
			while True:
				time.sleep(1)
		except KeyboardInterrupt:
			observer.stop()
		observer.join()